#!/bin/sh

#
# Init script to start and stop the aesdchar driver
#

start() {
    echo "Starting aesdchar..."
    aesdchar_load
    echo "OK"
}

stop() {
    echo "Stopping aesdchar..."
    aesdchar_unload
    echo "OK"
}

restart() {
    echo "Restarting aesdchar"
    stop
    start
}

case "$1" in
    start)
        start
        ;;
    stop)
        stop
        ;;
    restart | reload)
        restart
        ;;
    *)
        echo "Usage: $0 {start|stop|restart}"
        exit 1
        ;;
esac

exit $?
